import json
import os
from typing import Optional, Tuple, List, Dict, Any, Union
from datetime import datetime
from pathlib import Path
from openai import OpenAI
import fire

import numpy as np
import torch
from sb3_contrib.ppo_mask import MaskablePPO
from stable_baselines3.common.callbacks import BaseCallback

from alphagen.data.expression import Expression, Operators, Feature, FeatureType, Ref, StockData
from alphagen.data.parser import ExpressionParser
from alphagen.models.linear_alpha_pool import LinearAlphaPool, MseAlphaPool
from alphagen.rl.env.wrapper import AlphaEnv
from alphagen.rl.policy import LSTMSharedNet
from alphagen.utils import reseed_everything, get_logger
from alphagen.rl.env.core import AlphaEnvCore
from alphagen_qlib.calculator import QLibStockDataCalculator
from alphagen_qlib.stock_data import initialize_qlib
from alphagen_llm.client import ChatClient, OpenAIClient, ChatConfig
from alphagen_llm.prompts.system_prompt import EXPLAIN_WITH_TEXT_DESC
from alphagen_llm.prompts.interaction import InterativeSession, DefaultInteraction
from alphagen_llm.prompts.feedback_interaction import FeedbackInteraction

from alphagen_llm.feedback import (
    compute_alpha_metrics,
    call_critique_llm,
    call_fixer_llm,
    call_improvement_llm,
    run_feedback_loop_on_alphas,
)
from alphagen_llm.llm_alpha_stats_utils import (
    init_llm_alpha_stats,
    record_llm_alpha,
    record_survival,
    save_llm_alpha_stats,
    _save_survival_data,
    _plot_alpha_survival
)

import warnings
warnings.filterwarnings('ignore', message='.*Gym has been unmaintained.*')


def read_alphagpt_init_pool(seed: int) -> List[Expression]:
    DIR = "./out/llm-tests/interaction"
    parser = build_parser()
    for path in Path(DIR).glob(f"v0_{seed}*"):
        with open(path / "report.json") as f:
            data = json.load(f)
            pool_state = data[-1]["pool_state"]
            return [parser.parse(expr) for expr, _ in pool_state]
    return []


def build_parser() -> ExpressionParser:
    return ExpressionParser(
        Operators,
        ignore_case=True,
        non_positive_time_deltas_allowed=False,
        additional_operator_mapping={
            "Max": ["Greater"],
            "Min": ["Less"],
            "Delta": ["Sub"]
        }
    )


def build_chat_client(log_dir: str) -> ChatClient:
    logger = get_logger("llm", os.path.join(log_dir, "llm.log"))
    return OpenAIClient(
        client=OpenAI(),
        config=ChatConfig(
            system_prompt=EXPLAIN_WITH_TEXT_DESC,
            logger=logger
        )
    )


class CustomCallback(BaseCallback):
           
    def __init__(
        self,
        save_path: str,
        test_calculators: List[QLibStockDataCalculator],
        verbose: int = 0,
        chat_session: Optional[InterativeSession] = None,
        llm_every_n_steps: int = 25_000,
        drop_rl_n: int = 5,
        hyperparameters: Optional[Dict[str, Any]] = None
    ):
        super().__init__(verbose)
        self.save_path = save_path
        self.test_calculators = test_calculators
        os.makedirs(self.save_path, exist_ok=True)

        self.llm_use_count = 0
        self.last_llm_use = 0
        self.obj_history: List[Tuple[int, float]] = []
        self.llm_every_n_steps = llm_every_n_steps
        self.chat_session = chat_session
        self._drop_rl_n = drop_rl_n
        self.hyperparameters = hyperparameters or {}
        self.start_time = datetime.now()
        self.metrics_history: List[Dict[str, Any]] = []
        # Track alpha origins and survival
        self.alpha_origins: Dict[int, str] = {}  # alpha_id -> 'llm' or 'rl'
        self.alpha_birth_times: Dict[int, int] = {}  # alpha_id -> timestep born
        self.alpha_survival_history: Dict[int, Dict[str, Any]] = {}  # alpha_id -> survival data
        self.expr_to_id: Dict[str, int] = {}  # expression string -> unique id
        self.llm_expr_strs: set = set()  # Expressions generated by LLM (from initial pool load)
        self.improvement_expr_strs: set = set()  # Expressions from improvement LLM
        self.next_alpha_id = 0
        # For LLM/improvement LLM alpha stats
        self.llm_alpha_stats = init_llm_alpha_stats()

    def register_llm_pool_exprs(self, exprs: List[Expression]) -> None:
        """Register LLM-generated expressions from initial pool load."""
        for expr in exprs:
            self.llm_expr_strs.add(str(expr))
        print(f"[DEBUG] Registered {len(exprs)} initial LLM-generated expressions")
    
    def _on_step(self) -> bool:
        return True

    def _on_rollout_end(self) -> None:
        # Track alpha births and deaths before recording metrics
        self._update_alpha_tracking()
        
        if self.chat_session is not None:
            self._try_use_llm()

        self.logger.record('pool/size', self.pool.size)
        self.logger.record('pool/significant', (np.abs(self.pool.weights[:self.pool.size]) > 1e-4).sum())
        self.logger.record('pool/best_ic_ret', self.pool.best_ic_ret)
        self.logger.record('pool/eval_cnt', self.pool.eval_cnt)
        n_days = sum(calculator.data.n_days for calculator in self.test_calculators)
        ic_test_mean, rank_ic_test_mean = 0., 0.
        for i, test_calculator in enumerate(self.test_calculators, start=1):
            ic_test, rank_ic_test = self.pool.test_ensemble(test_calculator)
            ic_test_mean += ic_test * test_calculator.data.n_days / n_days
            rank_ic_test_mean += rank_ic_test * test_calculator.data.n_days / n_days
            self.logger.record(f'test/ic_{i}', ic_test)
            self.logger.record(f'test/rank_ic_{i}', rank_ic_test)
        self.logger.record(f'test/ic_mean', ic_test_mean)
        self.logger.record(f'test/rank_ic_mean', rank_ic_test_mean)
        
        # Record metrics for report
        self.metrics_history.append({
            'timestep': self.num_timesteps,
            'pool_size': self.pool.size,
            'pool_significant': int((np.abs(self.pool.weights[:self.pool.size]) > 1e-4).sum()),
            'best_ic_ret': float(self.pool.best_ic_ret),
            'ic_test_mean': float(ic_test_mean),
            'rank_ic_test_mean': float(rank_ic_test_mean)
        })
        
        self.save_checkpoint()

    def _update_alpha_tracking(self) -> None:
        """Track birth/death of alphas in the pool."""
        state = self.pool.state
        current_exprs = {str(state['exprs'][i]): i for i in range(self.pool.size)}
        
        # Mark new alphas
        for expr_str in current_exprs:
            if expr_str not in self.expr_to_id:
                alpha_id = self.next_alpha_id
                self.next_alpha_id += 1
                self.expr_to_id[expr_str] = alpha_id
                self.alpha_birth_times[alpha_id] = self.num_timesteps
                # Determine origin: check if LLM, improvement, or RL
                if expr_str in self.llm_expr_strs:
                    self.alpha_origins[alpha_id] = 'llm'
                    origin = 'llm'
                elif expr_str in self.improvement_expr_strs:
                    self.alpha_origins[alpha_id] = 'improvement'
                    origin = 'improvement'
                else:
                    self.alpha_origins[alpha_id] = 'rl'
                    origin = 'rl'
                self.alpha_survival_history[alpha_id] = {
                    'alpha_id': alpha_id,
                    'expression': expr_str,
                    'origin': origin,
                    'birth_timestep': self.num_timesteps,
                    'death_timestep': None,
                    'survival_steps': None
                }
        
        # Mark alphas that died (were removed)
        for expr_str, alpha_id in list(self.expr_to_id.items()):
            if expr_str not in current_exprs and self.alpha_survival_history[alpha_id]['death_timestep'] is None:
                self.alpha_survival_history[alpha_id]['death_timestep'] = self.num_timesteps
                self.alpha_survival_history[alpha_id]['survival_steps'] = (
                    self.num_timesteps - self.alpha_birth_times[alpha_id]
                )

    def save_checkpoint(self):
        path = os.path.join(self.save_path, f'{self.num_timesteps}_steps')
        self.model.save(path)   # type: ignore
        if self.verbose > 1:
            print(f'Saving model checkpoint to {path}')
        with open(f'{path}_pool.json', 'w') as f:
            json.dump(self.pool.to_json_dict(), f)

    def show_pool_state(self):
        state = self.pool.state
        print('---------------------------------------------')
        for i in range(self.pool.size):
            weight = state['weights'][i]
            expr_str = str(state['exprs'][i])
            ic_ret = state['ics_ret'][i]
            print(f'> Alpha #{i}: {weight}, {expr_str}, {ic_ret}')
        print(f'>> Ensemble ic_ret: {state["best_ic_ret"]}')
        print('---------------------------------------------')

    def _try_use_llm(self) -> None:
        n_steps = self.num_timesteps
        if n_steps - self.last_llm_use < self.llm_every_n_steps:
            return
        self.last_llm_use = n_steps
        self.llm_use_count += 1
        
        assert self.chat_session is not None
        self.chat_session.client.reset()
        logger = self.chat_session.logger
        logger.debug(
            f"[Step: {n_steps}] Trying to invoke LLM (#{self.llm_use_count}): "
            f"IC={self.pool.best_ic_ret:.4f}, obj={self.pool.best_ic_ret:.4f}")

        try:
            remain_n = max(0, self.pool.size - self._drop_rl_n)
            remain = self.pool.most_significant_indices(remain_n)
            
            # Record LLM alphas before they're added
            pre_llm_exprs = {str(self.pool.state['exprs'][i]) for i in range(self.pool.size)}
            
            self.pool.leave_only(remain)
            self.chat_session.update_pool(self.pool)
            
            # Track newly added alphas as LLM-generated for origin marking
            post_llm_exprs = {str(self.pool.state['exprs'][i]) for i in range(self.pool.size)}
            new_exprs = post_llm_exprs - pre_llm_exprs
            # Add to the set so they'll be marked as 'llm' origin when tracked
            self.llm_expr_strs.update(new_exprs)
            print(f"[DEBUG] Marked {len(new_exprs)} new alphas as LLM-generated")
        except Exception as e:
            logger.warning(f"LLM invocation failed due to {type(e)}: {str(e)}")

    @property
    def pool(self) -> LinearAlphaPool:
        assert(isinstance(self.env_core.pool, LinearAlphaPool))
        return self.env_core.pool

    @property
    def env_core(self) -> AlphaEnvCore:
        return self.training_env.envs[0].unwrapped  # type: ignore

    def _on_training_end(self) -> None:
        print(f"[DEBUG] _on_train_end called at timestep {self.num_timesteps}")

        self.save_report()

    def save_report(self) -> None:
        """Save comprehensive report with hyperparameters, metrics, and alphas."""
        state = self.pool.state
        end_time = datetime.now()
        
        print(f"[DEBUG] save_report called, alpha_survival_history size: {len(self.alpha_survival_history)}")
        # Mark surviving alphas
        for expr_str, alpha_id in self.expr_to_id.items():
            if self.alpha_survival_history[alpha_id]['death_timestep'] is None:
                self.alpha_survival_history[alpha_id]['death_timestep'] = self.num_timesteps
                self.alpha_survival_history[alpha_id]['survival_steps'] = (
                    self.num_timesteps - self.alpha_birth_times[alpha_id]
                )
        
        # Format: datetime_{name_of_script}_{test_ic}
        test_ic = self.metrics_history[-1]['ic_test_mean'] if self.metrics_history else 0.0
        timestamp = end_time.strftime("%Y%m%d_%H%M%S")
        filename = f"{timestamp}_rl_{test_ic:.4f}.json"
        filepath = os.path.join(self.save_path, filename)
        
        report = {
            'metadata': {
                'start_time': self.start_time.isoformat(),
                'end_time': end_time.isoformat(),
                'duration_seconds': (end_time - self.start_time).total_seconds(),
                'total_timesteps': self.num_timesteps
            },
            'hyperparameters': self.hyperparameters,
            'final_metrics': {
                'pool_size': self.pool.size,
                'best_ic_ret': float(self.pool.best_ic_ret),
                'final_ic_test_mean': self.metrics_history[-1]['ic_test_mean'] if self.metrics_history else 0.0,
                'final_rank_ic_test_mean': self.metrics_history[-1]['rank_ic_test_mean'] if self.metrics_history else 0.0
            },
            'metrics_history': self.metrics_history,
            'alphas': [
                {
                    'index': i,
                    'weight': float(state['weights'][i]),
                    'expression': str(state['exprs'][i]),
                    'ic_ret': float(state['ics_ret'][i])
                }
                for i in range(self.pool.size)
            ]
        }
        
        with open(filepath, 'w') as f:
            json.dump(report, f, indent=2)
        
        if self.verbose > 0:
            print(f'Saved comprehensive report to {filepath}')
        
        # Save alpha survival data (now using imported function)
        _save_survival_data(self.alpha_survival_history, self.save_path, timestamp, self.num_timesteps, verbose=self.verbose)

        # Save LLM alpha stats
        record_survival(self.llm_alpha_stats, self.alpha_survival_history)
        save_llm_alpha_stats(self.llm_alpha_stats, self.save_path, verbose=self.verbose)

    @property
    def pool(self) -> LinearAlphaPool:
        assert(isinstance(self.env_core.pool, LinearAlphaPool))
        return self.env_core.pool

    @property
    def env_core(self) -> AlphaEnvCore:
        return self.training_env.envs[0].unwrapped  # type: ignore

    def _on_training_end(self) -> None:
        print(f"[DEBUG] _on_train_end called at timestep {self.num_timesteps}")

        self.save_report()

    def save_report(self) -> None:
        """Save comprehensive report with hyperparameters, metrics, and alphas."""
        state = self.pool.state
        end_time = datetime.now()
        
        print(f"[DEBUG] save_report called, alpha_survival_history size: {len(self.alpha_survival_history)}")
        # Mark surviving alphas
        for expr_str, alpha_id in self.expr_to_id.items():
            if self.alpha_survival_history[alpha_id]['death_timestep'] is None:
                self.alpha_survival_history[alpha_id]['death_timestep'] = self.num_timesteps
                self.alpha_survival_history[alpha_id]['survival_steps'] = (
                    self.num_timesteps - self.alpha_birth_times[alpha_id]
                )
        
        # Format: datetime_{name_of_script}_{test_ic}
        test_ic = self.metrics_history[-1]['ic_test_mean'] if self.metrics_history else 0.0
        timestamp = end_time.strftime("%Y%m%d_%H%M%S")
        filename = f"{timestamp}_rl_{test_ic:.4f}.json"
        filepath = os.path.join(self.save_path, filename)
        
        report = {
            'metadata': {
                'start_time': self.start_time.isoformat(),
                'end_time': end_time.isoformat(),
                'duration_seconds': (end_time - self.start_time).total_seconds(),
                'total_timesteps': self.num_timesteps
            },
            'hyperparameters': self.hyperparameters,
            'final_metrics': {
                'pool_size': self.pool.size,
                'best_ic_ret': float(self.pool.best_ic_ret),
                'final_ic_test_mean': self.metrics_history[-1]['ic_test_mean'] if self.metrics_history else 0.0,
                'final_rank_ic_test_mean': self.metrics_history[-1]['rank_ic_test_mean'] if self.metrics_history else 0.0
            },
            'metrics_history': self.metrics_history,
            'alphas': [
                {
                    'index': i,
                    'weight': float(state['weights'][i]),
                    'expression': str(state['exprs'][i]),
                    'ic_ret': float(state['ics_ret'][i])
                }
                for i in range(self.pool.size)
            ]
        }
        
        with open(filepath, 'w') as f:
            json.dump(report, f, indent=2)
        
        if self.verbose > 0:
            print(f'Saved comprehensive report to {filepath}')
        
        # Save alpha survival data (now using imported function)
        _save_survival_data(self.alpha_survival_history, self.save_path, timestamp, self.num_timesteps, verbose=self.verbose)

        # Save LLM alpha stats
        record_survival(self.llm_alpha_stats, self.alpha_survival_history)
        save_llm_alpha_stats(self.llm_alpha_stats, self.save_path, verbose=self.verbose)

def run_single_experiment(
    seed: int = 0,
    instruments: str = "csi300",
    pool_capacity: int = 20,
    steps: int = 200_000,
    alphagpt_init: bool = False,
    use_llm: bool = False,
    llm_every_n_steps: int = 25_000,
    drop_rl_n: int = 5,
    llm_replace_n: int = 3,
    feedback_loop: bool = False,
    feedback_iter: int = 3,
    feedback_mode: str = "full",
    qlib_data_path: str = "~/.qlib/qlib_data/cn_data"
):
    reseed_everything(seed)
    initialize_qlib(qlib_data_path)

    llm_replace_n = 0 if not use_llm else llm_replace_n
    print(f"""[Main] Starting training process
    Seed: {seed}
    Instruments: {instruments}
    Pool capacity: {pool_capacity}
    Total Iteration Steps: {steps}
    AlphaGPT-Like Init-Only LLM Usage: {alphagpt_init}
    Use LLM: {use_llm}
    Invoke LLM every N steps: {llm_every_n_steps}
    Replace N alphas with LLM: {llm_replace_n}
    Drop N alphas before LLM: {drop_rl_n}
    Feedback loop enabled: {feedback_loop}
    Feedback iterations: {feedback_iter}""")

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    # tag = "rlv2" if llm_add_subexpr == 0 else f"afs{llm_add_subexpr}aar1-5"
    tag = (
        "agpt" if alphagpt_init else
        "rl" if not use_llm else
        f"llm_d{drop_rl_n}"+ (f"_feedback{feedback_iter}_{feedback_mode}" if feedback_loop else ""))
    name_prefix = f"{instruments}_{pool_capacity}_{seed}_{timestamp}_{tag}"
    save_path = os.path.join("./out/results", name_prefix)
    os.makedirs(save_path, exist_ok=True)

    device = torch.device("cuda:0")
    close = Feature(FeatureType.CLOSE)
    target = Ref(close, -20) / close - 1

    def get_dataset(start: str, end: str) -> StockData:
        return StockData(
            instrument=instruments,
            start_time=start,
            end_time=end,
            device=device
        )

    segments = [
        #HARLA  
        ("2012-01-01", "2021-12-31"),
        ("2022-01-01", "2022-06-30"),
        ("2022-07-01", "2022-12-31"),
        ("2023-01-01", "2023-06-30")
    ]
    datasets = [get_dataset(*s) for s in segments]
    calculators = [QLibStockDataCalculator(d, target) for d in datasets]

    def build_pool(exprs: List[Expression]) -> LinearAlphaPool:
        pool = MseAlphaPool(
            capacity=pool_capacity,
            calculator=calculators[0],
            ic_lower_bound=None,
            l1_alpha=5e-3,# original , regularisation to shrink alpha weights
            device=device
        )
        if len(exprs) != 0:
            pool.force_load_exprs(exprs)
        return pool

    chat, inter, pool = None, None, build_pool([])
    if alphagpt_init:
        pool = build_pool(read_alphagpt_init_pool(seed))
    elif use_llm:
        chat = build_chat_client(save_path)
        
        # Initialize llm_alpha_stats that will be shared with both interaction types
        llm_alpha_stats = init_llm_alpha_stats()
        
        # choose interaction type based on feedback_loop flag
        if feedback_loop:
            inter = FeedbackInteraction(
                build_parser(), chat, build_pool,
                calculator_train=calculators[0], calculators_test=calculators[1:],
                replace_k=llm_replace_n, forgetful=True,
                feedback_iter=feedback_iter,
                feedback_mode=feedback_mode,
                llm_alpha_stats=llm_alpha_stats
            )
        else:
            inter = DefaultInteraction(
                build_parser(), chat, build_pool,
                calculator_train=calculators[0], calculators_test=calculators[1:],
                replace_k=llm_replace_n, forgetful=True,
                llm_alpha_stats=llm_alpha_stats
            )
        pool = inter.run()
        print(f"[DEBUG] LLM pool initialization complete, pool size: {pool.size}")
    else:
        llm_alpha_stats = init_llm_alpha_stats()

    env = AlphaEnv(
        pool=pool,
        device=device,
        print_expr=True
    )
    
    hyperparams = {
        'seed': seed,
        'instruments': instruments,
        'pool_capacity': pool_capacity,
        'steps': steps,
        'alphagpt_init': alphagpt_init,
        'use_llm': use_llm,
        'llm_every_n_steps': llm_every_n_steps,
        'llm_replace_n': llm_replace_n,
        'drop_rl_n': drop_rl_n,
        'feedback_loop': feedback_loop,
        'feedback_iter': feedback_iter
    }
    
    # Now create checkpoint_callback after inter is initialized
    checkpoint_callback = CustomCallback(
        save_path=save_path,
        test_calculators=calculators[1:],
        verbose=1,
        chat_session=inter,
        llm_every_n_steps=llm_every_n_steps,
        drop_rl_n=drop_rl_n,
        hyperparameters=hyperparams
    )
    # Share the llm_alpha_stats
    checkpoint_callback.llm_alpha_stats = llm_alpha_stats
    
    # Register initial LLM pool expressions for survival tracking
    if use_llm and pool.size > 0:
        # Get current pool expressions
        state = pool.state
        pool_exprs = [state['exprs'][i] for i in range(pool.size)]
        checkpoint_callback.register_llm_pool_exprs(pool_exprs)
    
    
    model = MaskablePPO(
        "MlpPolicy",
        env,
        policy_kwargs=dict(
            features_extractor_class=LSTMSharedNet,
            features_extractor_kwargs=dict(
                n_layers=2,
                d_model=128,
                dropout=0.1,
                device=device,
            ),
        ),
        gamma=1.,
        ent_coef=0.01,
        batch_size=128,
        tensorboard_log="./out/tensorboard",
        device=device,
        verbose=1,
    )
    model.learn(
        total_timesteps=steps,
        callback=checkpoint_callback,
        tb_log_name=name_prefix,
    )
    
    # Print LLM alpha stats at end
    if use_llm and checkpoint_callback.llm_alpha_stats:
        print("\n" + "="*80)
        print("LLM ALPHA STATISTICS")
        print("="*80)
        stats = checkpoint_callback.llm_alpha_stats
        for kind in ['original', 'improvement']:
            print(f"\n{kind.upper()} LLM:")
            print(f"  Valid: {stats[kind]['valid']}")
            print(f"  Invalid: {stats[kind]['invalid']}")
            print(f"  Fixed: {stats[kind]['fixed']}")
            total = stats[kind]['valid'] + stats[kind]['invalid']
            if total > 0:
                print(f"  Valid %: {100*stats[kind]['valid']/total:.2f}%")
        print("\n" + "="*80)


def main(
    random_seeds: Union[int, Tuple[int]] = 0,
    pool_capacity: int = 20,
    instruments: str = "csi300",
    alphagpt_init: bool = False,
    use_llm: bool = False,
    drop_rl_n: int = 5,
    steps: Optional[int] = None,
    llm_every_n_steps: int = 25000,
    feedback_loop: bool = False,
    feedback_iter: int = 3,
    feedback_mode: str = "full",
    qlib_data_path: str = "~/.qlib/qlib_data/cn_data"
):
    """
    :param random_seeds: Random seeds
    :param pool_capacity: Maximum size of the alpha pool
    :param instruments: Stock subset name
    :param alphagpt_init: Use an alpha set pre-generated by LLM as the initial pool
    :param use_llm: Enable LLM usage
    :param drop_rl_n: Drop n worst alphas before invoke the LLM
    :param steps: Total iteration steps
    :param llm_every_n_steps: Invoke LLM every n steps
    :param feedback_loop: Enable initial LLM feedback loop (critique/fix/improve)
    :param feedback_iter: Number of feedback iterations for initial LLM alphas
    :param feedback_mode: Type of feedback loop - 'full' (critique/fix/improve) or 'fix-only' (just fix syntax)
    """
    if isinstance(random_seeds, int):
        random_seeds = (random_seeds, )
    default_steps = {
        10: 28_000,
        20: 250_000,
        50: 300_000,
        100: 350_000
    }
    for s in random_seeds:
        run_single_experiment(
            seed=s,
            instruments=instruments,
            pool_capacity=pool_capacity,
            steps=default_steps[int(pool_capacity)] if steps is None else int(steps),
            alphagpt_init=alphagpt_init,
            drop_rl_n=drop_rl_n,
            use_llm=use_llm,
            llm_every_n_steps=llm_every_n_steps,
            feedback_loop=feedback_loop,
            feedback_iter=feedback_iter,
            feedback_mode=feedback_mode,
            qlib_data_path=qlib_data_path
        )


if __name__ == '__main__':
    fire.Fire(main)
