"""
Batch script to run RL experiments with multiple fixed random seeds.
Runs the same experiment 10 times with different seeds for statistical validation.
"""
import fire
import json
import numpy as np
from pathlib import Path
from scripts.rl import run_single_experiment
from datetime import datetime

def run_batch_experiments(
    pool_capacity: int = 20,
    instruments: str = "csi300",
    alphagpt_init: bool = False,
    use_llm: bool = False,
    drop_rl_n: int = 5,
    steps: int = 250_000,
    llm_every_n_steps: int = 25000,
    feedback_loop: bool = False,
    feedback_iter: int = 3,
    feedback_mode: str = "full"
):
    """
    Run experiments 10 times with different fixed random seeds and aggregate results.
    
    :param pool_capacity: Maximum size of the alpha pool
    :param instruments: Stock subset name
    :param alphagpt_init: Use an alpha set pre-generated by LLM as the initial pool
    :param use_llm: Enable LLM usage
    :param drop_rl_n: Drop n worst alphas before invoke the LLM
    :param steps: Total iteration steps
    :param llm_every_n_steps: Invoke LLM every n steps
    :param feedback_loop: Enable initial LLM feedback loop (critique/fix/improve)
    :param feedback_iter: Number of feedback iterations for initial LLM alphas
    :param feedback_mode: Type of feedback loop - 'full' or 'fix-only'
    """
    # Fixed random seeds for 10 runs
    random_seeds = tuple(range(0, 10))
    
    print(f"""[Batch Runner] Starting batch experiments
    Number of runs: {len(random_seeds)}
    Random seeds: {random_seeds}
    Pool capacity: {pool_capacity}
    Instruments: {instruments}
    Use LLM: {use_llm}
    Feedback loop: {feedback_loop}
    """)
    
    results = {
        'ic_test': [],
        'rank_ic_test': [],
        'icir_test': [],
        'rank_icir_test': [],
    }
    
    # Run experiment 10 times
    for i, seed in enumerate(random_seeds, 1):
        print(f"\n{'='*60}")
        print(f"[Batch] Run {i}/10 with seed {seed}")
        print(f"{'='*60}")
        
        run_single_experiment(
            seed=seed,
            instruments=instruments,
            pool_capacity=pool_capacity,
            steps=steps,
            alphagpt_init=alphagpt_init,
            use_llm=use_llm,
            llm_every_n_steps=llm_every_n_steps,
            drop_rl_n=drop_rl_n,
            feedback_loop=feedback_loop,
            feedback_iter=feedback_iter,
            feedback_mode=feedback_mode
        )
        
        # Extract metrics from the latest report file
        metrics = _extract_latest_metrics(seed)
        if metrics:
            results['ic_test'].append(metrics['ic_test'])
            results['rank_ic_test'].append(metrics['rank_ic_test'])
            results['icir_test'].append(metrics['icir_test'])
            results['rank_icir_test'].append(metrics['rank_icir_test'])
            print(f"[Batch] Extracted - IC: {metrics['ic_test']:.6f}, Rank IC: {metrics['rank_ic_test']:.6f}, "
                  f"ICIR: {metrics['icir_test']:.6f}, Rank ICIR: {metrics['rank_icir_test']:.6f}")
    
    # Compute and report statistics
    _report_batch_statistics(results, random_seeds, pool_capacity, instruments, use_llm, feedback_loop)


def _extract_latest_metrics(seed: int) -> dict:
    """Extract IC and Rank IC from the latest report JSON file for a given seed."""
    results_dir = Path("./out/results")
    
    # Find report files matching this seed
    matching_files = list(results_dir.glob(f"*_{seed}_*_*.json"))
    
    if not matching_files:
        print(f"[Warning] No report file found for seed {seed}")
        return None
    
    # Get the most recent file
    latest_file = max(matching_files, key=lambda p: p.stat().st_mtime)
    
    try:
        with open(latest_file, 'r') as f:
            report = json.load(f)
        
        final_metrics = report.get('final_metrics', {})
        return {
            'ic_test': final_metrics.get('final_ic_test_mean', 0.0),
            'rank_ic_test': final_metrics.get('final_rank_ic_test_mean', 0.0),
            'icir_test': final_metrics.get('final_icir_test_mean', 0.0),
            'rank_icir_test': final_metrics.get('final_rank_icir_test_mean', 0.0),
        }
    except Exception as e:
        print(f"[Error] Failed to extract metrics from {latest_file}: {e}")
        return None


def _report_batch_statistics(results, seeds, pool_capacity, instruments, use_llm, feedback_loop, llm_every_n_steps, drop_rl_n, feedback_iter, feedback_mode):
    """Compute and print mean/std for all metrics."""
    print(f"\n{'='*60}")
    print("[Batch Results Summary]")
    print(f"{'='*60}")
    print(f"Configuration:")
    print(f"  Seeds: {seeds}")
    print(f"  Pool Capacity: {pool_capacity}")
    print(f"  Instruments: {instruments}")
    print(f"  Use LLM: {use_llm}")
    print(f"  Feedback Loop: {feedback_loop}")
    print(f"  Feedback Mode: {feedback_mode}")
    print(f"  Drop RL N: {drop_rl_n}")
    print(f"  Feedback Iter: {feedback_iter}\n")
    
    metrics_summary = {
        'IC': results['ic_test'],
        'Rank IC': results['rank_ic_test'],
        'ICIR': results['icir_test'],
        'Rank ICIR': results['rank_icir_test'],
    }
    
    for metric_name, values in metrics_summary.items():
        if values:
            mean = np.mean(values)
            std = np.std(values)
            print(f"{metric_name}:")
            print(f"  Mean: {mean:.6f}")
            print(f"  Std:  {std:.6f}")
            print(f"  Values: {[f'{v:.6f}' for v in values]}\n")
    
    # Create summary filename with configuration
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    llm_tag = "llm" if use_llm else "nollm"
    feedback_tag = f"fb{feedback_iter}_{feedback_mode}" if feedback_loop else "nofb"
    summary_filename = f"batch_summary_pc{pool_capacity}_{llm_tag}_drn{drop_rl_n}_{feedback_tag}_{timestamp}.json"
    summary_file = Path("./out/results") / summary_filename
    summary_file.parent.mkdir(parents=True, exist_ok=True)
    
    summary = {
        'seeds': seeds,
        'pool_capacity': pool_capacity,
        'instruments': instruments,
        'use_llm': use_llm,
        'llm_every_n_steps': llm_every_n_steps,
        'drop_rl_n': drop_rl_n,
        'feedback_loop': feedback_loop,
        'feedback_iter': feedback_iter,
        'feedback_mode': feedback_mode,
        'ic_test': {
            'mean': float(np.mean(results['ic_test'])),
            'std': float(np.std(results['ic_test'])),
            'values': [float(v) for v in results['ic_test']]
        },
        'rank_ic_test': {
            'mean': float(np.mean(results['rank_ic_test'])),
            'std': float(np.std(results['rank_ic_test'])),
            'values': [float(v) for v in results['rank_ic_test']]
        },
        'icir_test': {
            'mean': float(np.mean(results['icir_test'])),
            'std': float(np.std(results['icir_test'])),
            'values': [float(v) for v in results['icir_test']]
        },
        'rank_icir_test': {
            'mean': float(np.mean(results['rank_icir_test'])),
            'std': float(np.std(results['rank_icir_test'])),
            'values': [float(v) for v in results['rank_icir_test']]
        }
    }
    
    with open(summary_file, 'w') as f:
        json.dump(summary, f, indent=2)
    
    print(f"[Batch] Summary saved to {summary_file}")


if __name__ == '__main__':
    fire.Fire(run_batch_experiments)